[package]
name = "irc_time"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3"
irc = "1.0.0"
tokio = { version = "1.0", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "net",
    "time",
] }